ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true

packages:
  - "packages/*"
  - "plugins/*"

onlyBuiltDependencies:
  - unrs-resolver

defines:
  - &codestyle-config ^4.1.1
  - &tailwindcss ^4.1.18

catalogs:
  build:
    "@tailwindcss/vite": *tailwindcss
    "@vitejs/plugin-vue": ^6.0.3
    electron-vite: ^5.0.0
    tailwindcss: *tailwindcss
    tsdown: ^0.18.3
    unplugin-auto-import: ^20.3.0
    unplugin-vue-components: ^30.0.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-router: ^0.19.1
    vite: ^7.3.0
    vite-plugin-vue-devtools: ^8.0.5
    vite-plugin-vue-meta-layouts: ^0.6.1
    vite-tsconfig-paths: ^6.0.3

  core:
    mrmime: ^2.0.1
    unctx: ^2.5.0

  dev:
    "@antfu/ni": ^28.0.0
    concurrently: ^9.2.1

  electron:
    "@electron-toolkit/preload": ^3.0.2
    "@electron-toolkit/utils": ^4.0.0
    electron: ^39.2.7
    electron-builder: ^26.4.0

  linting:
    "@so1ve/eslint-config": *codestyle-config
    "@so1ve/prettier-config": *codestyle-config
    eslint: ^9.39.2
    prettier: ^3.7.4

  shadcn-vue:
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    lucide-vue-next: ^0.562.0
    tailwind-merge: ^3.4.0
    tw-animate-css: ^1.4.0

  types:
    "@types/node": ^24.10.4

  typescript:
    "@typescript/native-preview": 7.0.0-dev.20251225.1
    typescript: ^5.9.3
    vue-tsc: ^3.2.1

  vue:
    vue: ^3.5.25
    vue-router: ^4.6.4
catalog:
  reka-ui: ^2.7.0
